FORMAT: 1A

# 易卡爱途 API
易卡爱途系统API遵循RESTful规范.
* **图片应该先通过后端上传至七牛云，获取url再发送至后端.**

# Group 上传图片

## 上传图片 [/images]
   所有图片通过这个接口存入七牛云

### 上传图片 [POST]

+ Request (application/json)
    + Attributes
        + image (object) - 图片对象

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

# Group 登录注册

## 管理员登录 [/login]
   管理员登录

### 登录 [POST]
    4S店管理员使用手机号和密码登录.

+ Request (application/json)
    + Attributes (BaseUser)

+ Response 200 (application/json)
    + Attributes (BaseUserInfo)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

## 注册管理员 [/register]

### 注册 [POST]
    为4S店注册一个管理员账号

+ Request (application/json)
    + Attributes (StoreInfo)
        + password (string) - 登录密码

+ Response 201 (application/json)

    + Attributes (BaseUserInfo)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

# Group 店员管理

## 店员管理 [/users/{user_id}/staffs/{staff_id}{?access_token}{?page}{?ipp}{?q}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + access_token (string) - 管理员token，有效时间2个小时

### 查询店员 [GET]
    查询店员

+ Parameters
     + page (number) - 第<page>页
     + ipp (number) - 每页<ipp>项
     + q (string)

         查询条件，格式如下，中间是加号:

         + name:张三+phone:12345668899

+ Response 200 (application/json)
    + Attributes
        + max_page (number) - 最大页数
        + staffs (array[StaffInfo]) - 店员列表

### 删除店员 [DELETE]
    删除店员

+ Parameters
    + staff_id (number) - 管理员唯一标识

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

### 修改店员信息 [PUT]
    修改店员信息

+ Parameters
    + staff_id (number) - 管理员唯一标识

+ Request (application/json)
    + Attributes
        + name (string) - 店员姓名
        + phone (number) - 手机号码，11位，前后端都要正则验证

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

# Group 账号管理

## 门店管理 [/users/{user_id}{?access_token}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + access_token (string) - 管理员token，有效时间2个小时

### 查询门店基本信息 [GET]
    查询门店基本信息

+ Response 200 (application/json)

    + Attributes (StoreInfo)
        + deposit (number) - 保证金金额
        + created_at (string) - 注册时间

### 修改门店基本信息 [PUT]
    修改门店基本信息

+ Request (application/json)
    + Attributes (StoreInfo)

+ Response 200 (application/json)

    + Attributes (StoreInfo)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

## 银行卡管理 [/users/{user_id}/bankcards{?access_token}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + access_token (string) - 管理员token，有效时间2个小时

### 查询银行卡 [GET]
    查询银行卡

+ Response 200 (application/json)
    + Attributes
        + bankcards (array[BankCardInfo]) - 银行卡列表

### 添加银行卡 [POST]
    添加银行卡

+ Request (application/json)
    + Attributes (BankCardInfo)

+ Response 201 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

### 删除银行卡 [DELETE]
    删除银行卡(为满足RESTful规范，把批量删除的参数放到body里，下同)

+ Request (application/json)
    + Attributes
        + card_ids (array[string]) - 银行卡id列表

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

## 保证金补足记录管理 [/users/{user_id}/deposits{?access_token}{?page}{?ipp}{?q}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + access_token (string) - 管理员token，有效时间2个小时

### 查询保证金补足记录 [GET]
    查询保证金补足记录

+ Parameters
     + page (number) - 第<page>页
     + ipp (number) - 每页<ipp>项
     + q (string)

        查询条件，格式如下，以加号:

        + state:0|1+time:2018年3月6日-2018年3月7日


+ Response 200 (application/json)
    + Attributes
        + max_page (number) - 最大页数
        + records (array[DepositRechargeRecordInfo]) - 保证金补足记录列表

### 删除补足记录 [DELETE]
    删除补足记录

+ Request (application/json)
    + Attributes
        + record_ids (array[number]) - 记录id列表

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

## 收账记录管理 [/users/{user_id}/receive_money_records{?access_token}{?page}{?ipp}{?q}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + access_token (string) - 管理员token，有效时间2个小时

### 查询收账记录 [GET]

+ Parameters
     + page (number) - 第<page>页
     + ipp (number) - 每页<ipp>项
     + q (string)

         查询条件，格式如下，中间是加号:

         + driver_name:王五+traded_at:2017年3月7日

+ Response 200 (application/json)
    + Attributes
        + max_page (number) - 最大页数
        + records (array[ReceiveMoneyRecordInfo]) - 结算记录

### 删除收账记录 [DELETE]

+ Request (application/json)
    + Attributes
        + rev_mon_ids (array[number]) - 收账记录id列表

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

# Group 订单管理

## 订单记录管理 [/users/{user_id}/orders/{type}{?access_token}{?page}{?ipp}{?q}{?driver_id}{?driver_password}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + type (number) - 订单类型

### 查询订单记录 [GET]

+ Parameters
     + access_token (string) - 管理员token，有效时间2个小时
     + page (number) - 第<page>页
     + ipp (number) - 每页<ipp>项
     + q (string)

         查询条件，格式如下，中间是加号:

         + state:0|1|-1+time:2018年3月6日-2018年3月7日

+ Response 200 (application/json)
    + Attributes
        + max_page (number) - 最大页数
        + records (array[OrderRecordInfo]) - 订单记录列表

### 添加订单 [POST]

+ Parameters
    + driver_id (number) - 司机id
    + driver_password (string) - 司机密码

+ Request (application/json)
    + Attributes
        + project_type (string) - 预约项目类型
        + project_descp (string) - 预约项目描述

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)


### 删除订单记录 [DELETE]

+ Parameters
    + access_token (string) - 管理员token，有效时间2个小时

+ Request (application/json)
    + Attributes
        + order_ids (array[string]) - 订单单号列表

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

## 订单操作 [/users/{user_id}/orders/{type}/{order_id}{?access_token}]

+ Parameters
     + user_id (number) - 管理员唯一标识
     + type (number) - 订单类型
     + order_id (number) - 订单单号
     + access_token (string) - 管理员token，有效时间2个小时

### 处理订单 [PUT]
    订单状态码: 0表示未处理，1表示已接受，-1表示已拒绝，初始订单状态为0

+ Request (application/json)
    + Attributes
        + state (number) - 1表示接受订单，-1表示拒绝订单

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

# Group 结算管理

## 结算记录管理 [/users/{user_id}/settle_account_records{?access_token}{?page}{?ipp}{?q}]

+ Parameters
    + user_id (number) - 管理员唯一标识
    + access_token (string) - 管理员token，有效时间2个小时

### 查询结算记录 [GET]

+ Parameters
     + page (number) - 第<page>页
     + ipp (number) - 每页<ipp>项
     + q (string)

         查询条件，格式如下，中间是加号:

         + state:0|1|2+set_acc_id:20180293231+driver_name:李四

+ Response 200 (application/json)
    + Attributes
        + max_page (number) - 最大页数
        + records (array[SettleAccountRecordInfo]) - 结算记录

### 删除结算记录 [DELETE]

+ Request (application/json)
    + Attributes
        + set_acc_ids (array[string]) - 结算单号列表

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)

## 结算操作 [/users/{user_id}/sa{?access_token}?state=2]

+ Parameters
     + user_id (number) - 管理员唯一标识
     + access_token (string) - 管理员token，有效时间2个小时

### 批量结算 [PUT]
    订单状态码: 0表示联保中，1表示待结算，2表示已结算

+ Request (application/json)
    + Attributes
        + set_acc_ids (array[string]) - 结算单号列表

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (ErrorInfo)


# Data Structures

## ErrorInfo (object)
+ statue_code (number) - 状态码
+ error_desc (string) - 错误描述，直接显示给用户

## BaseUser (object)
+ phone (number) - 手机号码，11位，前后端都要正则验证
+ password (string) - 登录密码

## BaseUserInfo (object)
+ id (number) - 用户唯一标识
+ name (string) - 名字
+ phone (number) - 手机号码，11位，前后端都要正则验证
+ role (number) - 用户角色, 0代表店长，1代表店员

## StoreInfo (object)
+ name (string) - 名字
+ phone (number) - 手机号码，11位，前后端都要正则验证
+ reserve_phone (number) - 备用手机号码，11位，前后端都要正则验证
+ company_name (string) - 服务网点
+ location (string) - 网点地址
+ id_card (string) - 身份证号
+ pic_head_url (string) - 身份证正面照url
+ pic_tail_url (string) - 身份证反面照url
+ service_type (string) - 服务类型

## BankCardInfo (object)
+ card_id (string) - 银行卡账号
+ owner_id_card (string) - 开户人身份证号
+ owner_name (string) - 开户人
+ type (string) - 银行卡类型
+ bank_name (string) - 银行名称

## DepositRechargeRecordInfo (object)
+ id (number) - 保证金记录唯一标识
+ recharge_money (number) - 补足金额
+ recharge_time (string) - 补足时间
+ current_deposit (number) - 当前保证金金额
+ state (number) - 补足状态，0表示不足，1表示充足

## OrderRecordInfo (object)
+ order_id (number) - 订单单号
+ driver_name (string) - 预约订单的司机姓名
+ created_at (string) - 预约时间
+ project_type (string) - 预约项目类型
+ project_descp (string) - 预约项目描述
+ state (number) - 状态，0，1，-1

## StaffInfo (object)
+ id (number) - 店员唯一标识
+ name (string) - 店员姓名
+ phone (number) - 手机号码，11位，前后端都要正则验证

## SettleAccountRecordInfo (object)
+ set_acc_id (string) - 结算单号
+ company_name (string) - 服务网点
+ driver_name (string) - 付款人
+ driver_phone (number) - 司机手机号码，11位，前后端都要正则验证
+ trade_money (number) - 付款金额
+ traded_at (string) - 付款时间，对于待结算和联保中，这个字段为空
+ state (number) - 状态，0，1，2

## ReceiveMoneyRecordInfo (object)
+ id (string) - 收账记录id
+ set_acc_id (string) - 结算单号
+ driver_name (string) - 付款人
+ traded_at (string) - 付款时间，对于待结算和联保中，这个字段为空
+ actual_money (number) - 实际金额